### PR TITLE
Work around hardcoded FairRoot paths in PCM

### LINKED ISSUE #1194: Unable to run binaries from aliBuild-based RPMs that use FairRoot, ROOT and cling
Can be reproduced with current alisw RPMs.
Here's a *non-exhaustive* list of executables that trigger this issue:
* O2: `benchTracker`, `conditions-client`, `digitizer-workflow`, `preclusterizer`, `benchClusterizer`;
* QC: `qcTaskLauncher`, `qcCheckerLauncher`, `qcConsumer`;
* Readout: `readout.exe` (v0.6.0, current status unknown).

In all cases cling seems to try to load some FairRoot headers, but it looks for them in the wrong paths. The FairRoot include dir has a completely flat hierarchy in both RPMs and aliBuild install dirs, yet cling seems to use other paths.
Making a symlink for a header eliminates that single error line (example: `qtTaskLauncher`'s cling wants a header at `source/FairMbsStreamSource.h`, if one goes to the include dir and makes a symlink `source/FairMbsStreamSource.h` that points to `../FairMbsStreamSource.h`, then that error line disappears).
This issue does not seem to happen with local aliBuild.
```
$ ./benchTracker 
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to teo-fpctl110.cern.ch:0.0
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairAnaSelector.h
   requested to autoload type FairAnaSelector
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRadGridManager.h
   requested to autoload type FairRadGridManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRadLenManager.h
   requested to autoload type FairRadLenManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRadMapManager.h
   requested to autoload type FairRadMapManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorter.h
   requested to autoload type FairRingSorter
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorterTask.h
   requested to autoload type FairSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorterTask.h
   requested to autoload type FairSink
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorterTask.h
   requested to autoload type FairRootManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorterTask.h
   requested to autoload type FairTask
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRingSorterTask.h
   requested to autoload type FairRingSorterTask
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRun.h
   requested to autoload type FairRun
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunAna.h
   requested to autoload type FairRunInfo
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunAna.h
   requested to autoload type FairRunAna
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunAnaProof.h
   requested to autoload type FairFileSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunAnaProof.h
   requested to autoload type FairRunAnaProof
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunSim.h
   requested to autoload type FairIon
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunSim.h
   requested to autoload type FairMCApplication
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunSim.h
   requested to autoload type FairParticle
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunSim.h
   requested to autoload type FairRunSim
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTSBufferFunctional.h
   requested to autoload type FairLink
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTSBufferFunctional.h
   requested to autoload type FairMultiLinkedData
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTSBufferFunctional.h
   requested to autoload type FairMultiLinkedData_Interface
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTSBufferFunctional.h
   requested to autoload type FairTimeStamp
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTSBufferFunctional.h
   requested to autoload type FairTSBufferFunctional
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairTrajFilter.h
   requested to autoload type FairTrajFilter
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairWriteoutBuffer.h
   requested to autoload type FairWriteoutBuffer
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairRunOnline.h
   requested to autoload type FairRunOnline
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for steer/FairLinkManager.h
   requested to autoload type FairLinkManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairBaseContFact.h
   requested to autoload type FairBaseContFact
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairBaseParSet.h
   requested to autoload type FairBaseParSet
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairGeoParSet.h
   requested to autoload type FairGeoParSet
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairDetector.h
   requested to autoload type FairModule
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairDetector.h
   requested to autoload type FairDetector
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairGeaneApplication.h
   requested to autoload type FairGeaneApplication
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairGenerator.h
   requested to autoload type FairGenerator
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairGenericStack.h
   requested to autoload type FairGenericStack
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairPrimaryGenerator.h
   requested to autoload type FairPrimaryGenerator
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairRunIdGenerator.h
   requested to autoload type FairRunIdGenerator
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairVolume.h
   requested to autoload type FairVolume
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sim/FairVolumeList.h
   requested to autoload type FairVolumeList
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairEventBuilder.h
   requested to autoload type FairRecoEventHeader
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairEventBuilder.h
   requested to autoload type FairEventBuilder
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairEventBuilderManager.h
   requested to autoload type FairEventBuilderManager
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairEventHeader.h
   requested to autoload type FairEventHeader
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairFileHeader.h
   requested to autoload type FairFileHeader
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairFileInfo.h
   requested to autoload type FairFileInfo
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairHit.h
   requested to autoload type FairHit
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairMCEventHeader.h
   requested to autoload type FairMCEventHeader
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairMCPoint.h
   requested to autoload type FairMCPoint
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairMesh.h
   requested to autoload type FairMesh
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairRadLenPoint.h
   requested to autoload type FairRadLenPoint
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairRadMapPoint.h
   requested to autoload type FairRadMapPoint
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairTrackParam.h
   requested to autoload type FairTrackParam
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for event/FairPrintFairLinks.h
   requested to autoload type FairPrintFairLinks
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for field/FairField.h
   requested to autoload type FairField
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for field/FairFieldFactory.h
   requested to autoload type FairFieldFactory
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for field/FairPropagator.h
   requested to autoload type FairPropagator
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for field/FairRKPropagator.h
   requested to autoload type FairRKPropagator
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairMixedSource.h
   requested to autoload type FairMixedSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairOnlineSource.h
   requested to autoload type FairUnpack
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairOnlineSource.h
   requested to autoload type FairOnlineSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for sink/FairRootFileSink.h
   requested to autoload type FairRootFileSink
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairLmdSource.h
   requested to autoload type FairMbsSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairLmdSource.h
   requested to autoload type FairLmdSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/FairRemoteSource.h
   requested to autoload type FairRemoteSource
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/MRevBuffer.h
   requested to autoload type REvent
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for source/MRevBuffer.h
   requested to autoload type MRevBuffer
Run on (4 X 2194.92 MHz CPU s)
2018-06-13 16:56:33
--------------------------------------------------------------------------------
Benchmark                         Time           CPU Iterations UserCounters...
--------------------------------------------------------------------------------
BenchTracking/tracking/1       2057 ns       2054 ns     341569 num=486.796k/s
BenchTracking/tracking/2       3551 ns       3542 ns     195720 num=282.362k/s
BenchTracking/tracking/3       5467 ns       5459 ns     130167 num=183.184k/s
BenchTracking/tracking/4       7468 ns       7466 ns      95114 num=133.944k/s
BenchTracking/tracking/5       9954 ns       9938 ns      73172 num=100.624k/s
BenchTracking/tracking/6      12822 ns      12810 ns      53100 num=78.0611k/s
BenchTracking/tracking/7      15564 ns      15561 ns      45250 num=64.2618k/s
BenchTracking/tracking/8      18347 ns      18346 ns      39361 num=54.5087k/s
```

Modules:
```$ module list
Currently Loaded Modulefiles:
  1) BASE/1.0                          7) Monitoring/v1.7.2-1              13) ZeroMQ/v4.1.5-6                  19) GSL/v1.16-26                     25) Vc/1.3.3-4                       31) dim/v20r20-4
  2) GCC-Toolchain/v6.2.0-alice1-4     8) Ppconsul/0.0.1-12                14) nanomsg/v1.0.0+git_c52f1bedca-1  20) Python-modules/1.0-16            26) ms_gsl/1-3                       32) ReadoutCard/v0.8.8-2
  3) libpng/v1.6.34-4                  9) Configuration/v1.5.0-2           15) msgpack/v2.1.5-1                 21) lzma/v5.2.3-1                    27) arrow/v0.9.0-alice1-2            33) Readout/v0.7.0-1
  4) FreeType/v2.6-35                 10) Common-O2/v1.2.5-1               16) DDS/2.0-6                        22) ROOT/v6-12-06-5                  28) O2/38d2bf591c_O2_DATAFLOW-1
  5) Python/v2.7.10-33                11) InfoLogger/v1.0.5-2              17) FairMQ/v1.2.4-2                  23) FairRoot/717dccd866-1            29) QualityControl/v0.6-1
  6) boost/v1.66.0-4                  12) FairLogger/v1.2.0-1              18) protobuf/v3.5.2-1                24) DataSampling/v0.1.2-1            30) PDA/12.0.0-4
```

### PR DESCRIPTION
**Pull request by teo**
The present workaround creates a directory `include_tree` alongside `include` in the install directory. `include_tree` contains a number of directory symlinks, all of which point back to `include`: this way we make sure that no matter what FairRoot header is requested by its build dir path, the `#include` statement will find its way to the right file.
We also add the `include_tree` directory to `ROOT_INCLUDE_PATH`.

I am fully aware of the horror of what I'm doing here, but at the moment we are stuck with barely functional FairRoot when using RPMs and CVMFS, which blocks system integration efforts.

Fixes #1194.

This should be removed once FairRoot fixes their build system.

### CODE REVIEW

File: fairroot.sh [hunk 1]
```diff
@@ -70,6 +70,13 @@ cmake $SOURCEDIR
 
 cmake --build . -- -j$JOBS install
 
+INCLUDE_TREE="$INSTALLROOT/include_tree"
```
Comment (dberzano) [inline fairroot.sh]: Can we do this inside `include` without creating a new directory?

File: fairroot.sh [hunk 2]
```diff
@@ -70,6 +70,13 @@ cmake $SOURCEDIR
...
+mkdir -p $INCLUDE_TREE
+SUBDIRS="source sink field event sim steer"
+for dir in $SUBDIRS; do
```
Comment (dberzano) [inline fairroot.sh]: Should be:

```bash
for DIR in source sing field event sim steer; do
  ln -nfs ../include $INSTALLROOT/include/$DIR
done
```

File: fairroot.sh [hunk 3]
```diff
@@ -106,5 +113,6 @@ setenv CONFIG_DIR \$::env(VMCWORKDIR)/common/gconfig
 prepend-path PATH \$::env(FAIRROOT_ROOT)/bin
 prepend-path LD_LIBRARY_PATH \$::env(FAIRROOT_ROOT)/lib
 prepend-path ROOT_INCLUDE_PATH \$::env(FAIRROOT_ROOT)/include
+prepend-path ROOT_INCLUDE_PATH \$::env(FAIRROOT_ROOT)/include_tree
```
Comment (dberzano) [inline fairroot.sh]: Not needed if we do everything inside `include`

**Comment by dberzano** [comment]
@teo thanks for taking care of this! Your solution is a smart workaround. I have requested some minor modifications.

File: fairroot.sh (hunk 1 above)
Comment (teo) [reply fairroot.sh]: We can, but then we pollute the "real" include directory (which is picked up by the build systems of other packages) with spurious header paths.

File: fairroot.sh (hunk 3 above)
Comment (teo) [reply fairroot.sh]: I've thought of this, but I figured it makes sense to split the two, as `include_tree` is a total fake, just for cling.
Furthermore, if we created those dir symlinks inside `include` pointing to `..`, we'd get a cycle, which is not bad in itself but we de facto generate even more spurious paths.

File: fairroot.sh (hunk 2 above)
Comment (teo) [reply fairroot.sh]: Yep, I'm fixing this.

Please confirm if you still want me to use the single `include` dir for all the symlinks.

File: fairroot.sh (hunk 3 above)
Comment (dberzano) [reply fairroot.sh]: Loops aren't much of a problem as long as we use symlinks and not hard links (`find`, for instance, should deal with them neatly).

File: fairroot.sh (hunk 2 above)
Comment (dberzano) [reply fairroot.sh]: Sure, I prefer to have a single `include` directory, thanks!

File: fairroot.sh (hunk 1 above)
Comment (dberzano) [reply fairroot.sh]: In principle if something (like CMake) looks for a header under `include` it will find it many times now, but the first one should win. Let's see if the test build works.

File: fairroot.sh (hunk 3 above)
Comment (teo) [reply fairroot.sh]: Yes, but that's what I meant: loops are not bad in itself, but they mean that a downstream can do something like `#include <sink/sink/sink/sink/sink/sink/FairSomethingSomething.h>`.
Keeping a separate fake include dir which is only added to `ROOT_INCLUDE_PATH` and is not a standard include path picked up by `find_package` avoids this issue.

**Comment by dberzano** [comment]
Thanks. Tests will speak.

**Comment by dberzano** [comment]
Usual unrelated error.
